# Generated by Django 4.1 on 2024-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantdisease",
            name="image",
            field=models.ImageField(
                default="d0af38a2527645f6.jpg",
                upload_to="C:/Users/hp/Final Year Project/backend/images",
            ),
        ),
    ]
