# Generated by Django 4.1 on 2024-02-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_plantdisease_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantdisease",
            name="image",
        ),
    ]
